# Generated by Django 5.0.1 on 2024-03-20 18:13

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Kids",
            new_name="InSale",
        ),
        migrations.DeleteModel(
            name="Man",
        ),
        migrations.DeleteModel(
            name="Sale",
        ),
        migrations.DeleteModel(
            name="Woman",
        ),
    ]
