# Generated by Django 5.0.1 on 2024-03-19 20:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Man",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("photo", models.ImageField(upload_to=None)),
                ("product_name", models.CharField(max_length=60)),
                ("description", models.TextField()),
            ],
        ),
    ]
