# Generated by Django 5.0.1 on 2024-03-20 19:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0003_kids_man_woman"),
    ]

    operations = [
        migrations.AlterField(
            model_name="insale",
            name="photo",
            field=models.ImageField(upload_to="img"),
        ),
        migrations.AlterField(
            model_name="kids",
            name="photo",
            field=models.ImageField(upload_to="img"),
        ),
        migrations.AlterField(
            model_name="man",
            name="photo",
            field=models.ImageField(upload_to="img"),
        ),
        migrations.AlterField(
            model_name="woman",
            name="photo",
            field=models.ImageField(upload_to="img"),
        ),
    ]
