# Generated by Django 5.0.1 on 2024-03-20 19:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0005_alter_insale_photo_alter_man_photo_alter_woman_photo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="kids",
            name="photo",
            field=models.ImageField(upload_to="product/static/img/woman"),
        ),
        migrations.AlterField(
            model_name="man",
            name="photo",
            field=models.ImageField(upload_to="product/static/img/man_img"),
        ),
        migrations.AlterField(
            model_name="woman",
            name="photo",
            field=models.ImageField(upload_to="product/static/img/woman"),
        ),
    ]
