# Generated by Django 5.0.1 on 2024-03-20 20:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "product",
            "0008_alter_insale_photo_alter_kids_photo_alter_man_photo_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="insale",
            name="price",
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name="kids",
            name="price",
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name="man",
            name="price",
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name="woman",
            name="price",
            field=models.FloatField(default=0.0),
        ),
    ]
